// eslint-disable-next-line import/prefer-default-export
export const routes = {
  register: '/register',
  activate: '/activate',
  login: '/login',
  forgotPassword: '/forgot',
  linkExpired: '/LinkExpired',
  resetPassword: '/reset',
  passwordChanged: '/passwordChanged',
  categories: '/categories',
  category: '/category',
  addExcersise: '/add-exercise',
  editExcersise: '/edit-exercise',
  excersise: '/exercises:id',
  plans: '/plans',
  plan: '/plan',
  users: '/users',
  user: '/user',
  organizations: '/organizations',
  organizationUsers: '/organizationusers',
  organizationTrainer: '/organizationtrainers',
  organizationClients: '/organizationclients',
  trainers: '/trainers',
  clients: '/clients',
  myProfile: '/myprofile',
};
