export const routes = {
    register: '/register',
    activate: '/activate',
    login: '/login',
    forgotPassword: '/forgotpassword',
    categories: '/categories',
    category: '/category',
    addExcersise: '/add-exercise',
    editExcersise: '/edit-exercise',
    excersise: '/exercise',
    plans: '/plans',
    plan: '/plan',
    users: '/users',
    user: '/user',
    organizations: '/organizations',
    trainers: '/trainers',
    clients: '/clients',
    myProfile: '/myprofile',
  };
  